### ISSUE TITLE
Some module dependency is not loaded

### ISSUE THREAD

**Issue by Fs02** [skleeschulte/babel-plugin-transform-semantic-ui-react-imports#1]
Hi, thanks for this great plugins.

So, for example dropdown or search didn't work correctly without importing transition and menu component from react.

so I had to modify index.js to be like this:
```
/**
 * Import the global LESS files. Imports for component LESS files are added by
 * babel-plugin-transform-semantic-ui-react-imports depending on which components from semantic-ui-react are used.
 */

/* Global */
import 'semantic-ui-less/definitions/globals/reset.less';
import 'semantic-ui-less/definitions/globals/site.less';

import 'semantic-ui-less/definitions/modules/transition.less';
import 'semantic-ui-less/definitions/collections/menu.less';
```

**Comment by skleeschulte** [comment]
Thanks for reporting the issue. I'm not sure how these "additional" style dependencies should be handled though. Any thoughts on this?

**Comment by Fs02** [comment]
I'm not sure either, maybe the easiest way is to put this info in readme that some module dependency may needed to be included manually?

**Comment by skleeschulte** [comment]
I'll close this for now as the behaviour is now documented.
