### ISSUE TITLE
Plugin doesn't work with babel 7

### ISSUE THREAD

**Issue by austinfox** [skleeschulte/babel-plugin-transform-semantic-ui-react-imports#3]
I can't find any documentation for breaking changes to the options babel passes to plugins, but I'm fairly certain the structure of these options has changed and it is causing this plugin to no longer work. The problem occurs in the "pre" function:

```javascript
pre: function(state) {
        addedCssImports = {};
        addedLessImports = {};

        multipleStyleImportsChecked = false;

        foundLodashPluginWithIdSemanticReactUi = false;
        babelPluginLodashChecked = false;

        const lodashPlugins = state.opts.plugins.filter(function(plugin) {
            return plugin[0].key === 'lodash' || plugin[0].key === 'babel-plugin-lodash';
        });
```

Specifically this last part:
```javascript
const lodashPlugins = state.opts.plugins.filter(function(plugin) {
        return plugin[0].key === 'lodash' || plugin[0].key === 'babel-plugin-lodash';
});
```

The error I'm getting is this:
```
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: Cannot read property 'key' of undefined
    at /[path hidden for privacy]/node_modules/babel-plugin-transform-semantic-ui-react-imports/index.js:234:34
    at Array.filter (<anonymous>)
```

Logging the 'plugin' values in that loop shows that it is an object, not an array. The object does indeed have a 'key' property. If I modify the code to no longer treat the resulting 'plugin' value as an array, the error goes away:
```javascript
return plugin.key === 'lodash' || plugin.key === 'babel-plugin-lodash';
```

**Comment by austinfox** [comment]
Looks like there is an open pull request:
https://github.com/skleeschulte/babel-plugin-transform-semantic-ui-react-imports/pull/2

**Comment by skleeschulte** [comment]
Thanks for your investigation @austinfox. I finally merged @tcrossland's PR and changed the tests to run with Babel 6 and Babel 7.
